# Generated by Django 3.2.4 on 2021-07-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0002_alter_tps_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tps',
            options={'ordering': ('-fecha_entrega',)},
        ),
    ]
